import { CourseType,  } from '../enums/course-type.enum';
import { CourseStatus } from '../enums/course-status.enum';

export interface PublicCourse {
  id: number,
  user_id: number,
  cover_image: string,
  promo_video: string,
  title: string,
  description: string,
  sub_title: string,
  language: number,
  type: CourseType,
  status: CourseStatus,
  category_id: number,
  lessons_count: number,
  max_participants: number,
  level: number,
  definition: string,
  requirements: string,
  will_learn: string,
  certificate: number,
  link: string,
  trainer_id: number,
  price: number,
  discount_percent: number,
  currency: string,
  created_at: string,
  updated_at: string,
  address: string,
  slug: string,
  rate: number,
  first_lesson_date: string,
}
